### ISSUE TITLE
Setting the function name on latest name version

### ISSUE THREAD

**Issue by blakeembrey** [JsCommunity/make-error#10]
The current implementation for setting the function name appears to be broken on the latest node version. For reference, see https://travis-ci.org/blakeembrey/make-error-cause/builds/157755665. It's now inheriting `constructor` (inferred from the `constructor = function () { ... }` line) instead of being set.

**Comment by julien-f** [comment]
Thanks for your report :)

I am trying a new way to set the constructor name (#11), I hope it won't introduce any regression.

**Comment by julien-f** [comment]
Released as v1.2.1.
