### ISSUE TITLE
Special error not working, throwing cannot invoke constructor without new

### ISSUE THREAD

**Issue by idchlife** [JsCommunity/make-error#18]
https://runkit.com/idchlife/5a43b9242cef4c00139318c7

here is example of this error

**Comment by julien-f** [comment]
Thanks for your report, I'm investigating :)

**Comment by idchlife** [comment]
@julien-f could you possibly update npm package also?

Also, thank you for the library, it's very useful!

**Comment by julien-f** [comment]
It should with v1.3.1 if your environment supports [`Reflect.construct`](https://devdocs.io/javascript/global_objects/reflect/construct).

If not, simply avoid mixing `makeError()` (intended for ES5) and `BaseError` (intended for ES2015+).

**Comment by julien-f** [comment]
> Also, thank you for the library, it's very useful!

Glad it's helpful 😃
