### ISSUE TITLE
Attempted to assign to readonly property error

### ISSUE THREAD

**Issue by jamiemcl001** [JsCommunity/make-error#20]
**Description of the issue:** When invoking the getter of an errors `stack` property - this causes the property to be redefined and doesn't explicitly set the `writable` property back to true. On certain browsers (tested on iOS Safari - though it works fine on Desktop Chrome) this results in an `Attempted to assign to read-only property` unhandled exception to be thrown.

I've put together a little test project to demonstrate the issue, it can be found [here](https://github.com/jamiemcl001/make-error-testbed).

**Comment by julien-f** [comment]
Thanks for your excellent report, the fix has been released in 1.3.3.
