### ISSUE TITLE
Consider making properties enumerable

### ISSUE THREAD

**Issue by dls314** [JsCommunity/make-error#23]
I saw that stack, message, and name were not enumerable while trying to serialize a BaseError using JSON.stringify.

Was this a purposeful decision to match the weird behavior of error?

**Comment by dls314** [comment]
If not, would it be reasonable to use `enumerable: true` when calling defineProperty throughout index.js? If that sounds right, I'll send a seriously inexpert PR of the same.

**Comment by julien-f** [comment]
Closing this, feel free to comment if you have new info :slightly_smiling_face:
