### ISSUE TITLE
Subclassing a custom error class breaks name, instanceof flow in TypeScript

### ISSUE THREAD

**Issue by austince** [JsCommunity/make-error#27]
Hey there, thanks for maintaining this great package! 

I'm using the ES6 version with TypeScript (also targetting ES6). Everything works as documented until I subclass a custom error, in which case only the custom error superclass's name comes through, and InstanceOf no longer works as well.

```typescript
import { BaseError } from 'make-error';


class CustomBaseError extends BaseError {
}

class CustomError extends CustomBaseError {
}

const err = new CustomError();
console.log(err instanceof CustomError); // false
console.log(err instanceof CustomBaseError); // true
console.log(err instanceof BaseError); // true

console.log(err.name); // 'CustomBaseError'
```

Is this expected behavior/ perhaps just a TypeScript issue? 

I've found [a decent blog post](https://joefallon.net/2018/09/typescript-try-catch-finally-and-custom-errors/) which describes how to handle it in the `Best Practice – Be Specific with Errors` section, though unfortunately the official link to the TS docs is broken.

**Comment by austince** [comment]
As context, this is use case is very helpful for REST API errors, where it's nice to have one `BaseError` for common issues `NotFoundError`, `BadRequestError`, and then subclass those to more specific issues like `SchemaValidationError extends BadRequestError`.

**Comment by austince** [comment]
Or maybe I just mistyped in my tests cases ... sorry.

**Comment by julien-f** [comment]
No problem :smile: 

Have a nice day.
