### ISSUE TITLE
Testsuite 1.3.6 : failures with nodejs 12.19.0 and jest 26.6.3

### ISSUE THREAD

**Issue by SnarkBoojum** [JsCommunity/make-error#31]
I just unpacked the 1.3.6 tarball, went in, ran jest, and there were four failures:
- makeError(name) › derivable with › makeError(constructor)
- makeError(name) › derivable with › ES5 inheritance
- ES6 inheritance › derivable with › makeError(constructor)
- ES6 inheritance › derivable with › ES5 inheritance

The first two give Expected: "something" Received: "Error" ; the last two TypeError: Class constructor  cannot be invoked without 'new'.

**Comment by julien-f** [comment]
Thanks for your report, these use cases were always failing.

The tests cover all possible cases, unfortunately I do not know any implementation that can handle all of them.

Maybe it would be better to explicitly mark these tests should as skipped.

**Comment by SnarkBoojum** [comment]
Please, do! I'm packaging make-error for the Debian distribution, and I'm stuck because the test suite doesn't pass...

**Comment by SnarkBoojum** [comment]
Thanks!

**Comment by julien-f** [comment]
You're welcome :-)

Have a nice day.
